apiVersion: machine.talos.crossplane.io/v1alpha1
kind: ConfigurationApply
metadata:
  name: apply-worker-config
spec:
  forProvider:
    node: "192.168.120.87"  # Update with your Talos machine IP
    machineConfigurationRef:
      name: worker-machine-configuration
      namespace: default
      key: machine_configuration
    clientConfiguration:
      caCertificate: "insecure"
      clientCertificate: "insecure"
      clientKey: "insecure"
  providerConfigRef:
    name: default
